import { Geist} from "next/font/google";
import "./globals.css";
import Navbar from "./Navbar";
import Footer from "./Footer";

const geistSans = Geist({
  weight: "500",
  subsets: ["latin"],
});

const geistMono = Geist({
  weight:"600",
  subsets: ["latin"],
});

const geistMon = Geist({
  weight:"700",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      data-theme='light'
      suppressHydrationWarning
      className={`${geistSans.className} ${geistMono.className} ${geistMon.className} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <Navbar></Navbar>
        <main className="max-w-7xl mx-auto">
          {children}
        </main>
        <Footer></Footer>
      </body>
    </html>
  );
}
